env                                           = "dev"
region                                        = "us-east-1"
aws_account_number                            = "332281781429"
created_by                                    = "BizCloudExperts"
application                                   = "Omni Bio Rad Api Services"
omni_bio_rad_notification_emails              = "madhava.matta@bizcloudexperts.com"
api_key                                       = "Rf2hL9s4Gp7qW8xRf2hL9s4Gp7qW8x12"
lbn_send_endpoint                             = "https://api.logistics.eu.business-network.cloud.sap/http/v1/LbnFreightOrderForSubcontracting"
lbn_token_endpoint                            = "https://bn4lintegrationsuiteliveeu10-d2q5jmpt.authentication.eu10.hana.ondemand.com/oauth/token"
lbn_token_endpoint_request_client_id          = "sb-aaa08ad0-9ad0-4424-b088-fb5bc11c6524!b368405|it-rt-bn4lintegrationsuiteliveeu10-d2q5jmpt!b182722"
lbn_token_endpoint_request_client_secret      = "ff3bb9e8-76fb-43db-91fc-3b8623b9d84a$cr8AQtqP75YWf2trEvDMkcZgdSWg02K1GvQour5zECc="
update_source_db_endpoint                     = "https://dev-api.omnilogistics.com/updateSourceDb"
omni_wt_get_document_api_url                  = "https://websli.omnilogistics.com/wtTest/getwtdoc/v1/json/8495facb3355d4aab0197eadf1f484"
omni_wt_add_document_api_url                  = "https://wttest.omnilogistics.com/WTKServices/shipments.asmx"
omni_wt_create_shipment_api_url               = "https://wttest.omnilogistics.com/WTKServices/AirtrakShipment.asmx"
omni_bio_rad_bill_to_numbers                  = "8061,8062"
lbn_send_order_events_endpoint                = "https://api.logistics.eu.business-network.cloud.sap/http/http/v1/tracking/events"
lbn_send_billing_invoice_endpoint             = "https://api.logistics.eu.business-network.cloud.sap/http/v1/LogisticsInvoice"