env                                 = "prod"
region                              = "us-east-1"
aws_account_number                  = "332281781429"
created_by                          = "BizCloudExperts"
application                         = "Omni Bio Rad Api Services"
omni_bio_rad_notification_emails    = ["omnidev@bizcloudexperts.com","support@bizcloudexperts.com","madhava.matta@bizcloudexperts.com"]
api_key                             = "e75bc31db0ea4f9ba3377168f4462d54"
lbn_send_endpoint                   = "https://l20398-iflmap.hcisbp.eu1.hana.ondemand.com/http/v1/LbnFreightOrderForSubcontracting"
lbn_token_endpoint                  = "https://oauthasservices-a46089868.hana.ondemand.com/oauth2/api/v1/token?grant_type=client_credentials"
lbn_token_endpoint_request_username = "OMNILogisticsLiveSpace"
lbn_token_endpoint_request_password = "O6n!!3f4Ei$6*uU~9Fn7=5?X21jV#~~TmN1~!4"
update_source_db_endpoint           = "https://api.omnilogistics.com/updateSourceDb"
omni_wt_get_document_api_url        = "https://websli.omnilogistics.com/wtProd/getwtdoc/v1/json/83af3a69f59260887863087f55fd23"
omni_wt_add_document_api_url        = "https://worldtrak.omnilogistics.com/WTKServices/shipments.asmx"
omni_wt_create_shipment_api_url     = "https://worldtrak.omnilogistics.com/WTKServices/AirtrakShipment.asmx"
omni_bio_rad_bill_to_numbers        = "8061,8062"
lbn_send_order_events_endpoint      = "https://l20398-iflmap.hcisbp.eu1.hana.ondemand.com/http/http/v1/tracking/events"
lbn_send_billing_invoice_endpoint   = "https://l20398-iflmap.hcisbp.eu1.hana.ondemand.com/http/v1/LogisticsInvoice"
